### PR TITLE
Update to work with digestif 0.7

### PR DESCRIPTION
**Pull request by hcarty**
Small changes due to `Digestif.SHA256.t` being abstract now rather than just private.

### CODE REVIEW

**Comment by andersfugmann** [comment]
Thanks, 

I guess this is needed for a yet to be released version of digestif. 
I will merge and update the version requirement of digestif once released. 

Currently the travis build fails with 
```
#File "aws-s3/authorization.ml", line 18, characters 20-49:
#Error: Unbound value Digestif.SHA256.to_raw_string
#      ocamlc aws-s3/.aws_s3.objs/aws_s3__Authorization.{cmo,cmt} (exit 2)
#(cd _build/default && /home/travis/.opam/4.06.1/bin/ocamlc.opt -w -40 -g -bin-annot -I aws-s3/.aws_s3.objs -I /home/travis/.opam/4.06.1/lib/base -I /home/travis/.opam/4.06.1/lib/base/caml -I /home/travis/.opam/4.06.1/lib/base/shadow_stdlib -I /home/travis/.opam/4.06.1/lib/base64 -I /home/travis/.opam/4.06.1/lib/biniou -I /home/travis/.opam/4.06.1/lib/bytes -I /home/travis/.opam/4.06.1/lib/dig[...]
#File "aws-s3/authorization.ml", line 18, characters 20-49:
#Error: Unbound value Digestif.SHA256.to_raw_string
```

**Comment by hcarty** [comment]
Now that [digestif 0.7](http://opam.ocaml.org/packages/digestif/digestif.0.7/) is out I've updated the opam version constraint in this PR to match.  Hopefully the travis build works as well as my local tests have!

**Comment by hcarty** [comment]
The tests pass now.  Are there any other changes you'd like to include in this update?
